# Site settings 
title: "Grimoire" 
author: "Saph, thebombzen, Cogniss"
description:
  "A searchable D&D 5e spell list, sorted by class and level."
baseurl: "/Grimoire" # the subpath of your site, e.g. /blog/
url: "http://cogniss.github.io" # the base hostname & protocol for your site
source-url: "https://github.com/cogniss/Grimoire/"
permalink: "/:categories/:title"
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

# Build settings
markdown: kramdown
highlighter: rouge

# Site defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "spells"
